import argparse
import os
import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

def parse_args(argv=None):
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    g = p.add_argument_group('paths')
    g.add_argument('--model_path', required=True)
    g.add_argument('--data_dir', required=True)
    g.add_argument('--wheel_dir', default=None)
    g.add_argument('--out_dir', default='/kaggle/working/recant_out' if os.path.isdir('/kaggle/working') else './recant_out')
    g.add_argument('--tmp_dir', default=None)
    g.add_argument('--min_tmp_gb', type=float, default=5.0)
    g = p.add_argument_group('time / schedule')
    g.add_argument('--time_limit_hours', type=float, default=5.0)
    g.add_argument('--save_reserve_min', type=float, default=12.0)
    g.add_argument('--max_steps', type=int, default=None)
    g.add_argument('--warmup_steps', type=int, default=20)
    g.add_argument('--min_lr_ratio', type=float, default=0.1)
    g = p.add_argument_group('model')
    g.add_argument('--device', default='cuda')
    g.add_argument('--dtype', choices=['bf16', 'fp32'], default='bf16')
    g.add_argument('--no_fast', action='store_true')
    g.add_argument('--fast_disable', default='')
    g.add_argument('--profile_steps', default='')
    g.add_argument('--no_quantize', action='store_true')
    g.add_argument('--lora_r', type=int, default=128)
    g.add_argument('--lora_alpha', type=float, default=128.0)
    g.add_argument('--head_hidden', type=int, default=1024)
    g.add_argument('--n_bins', type=int, default=51)
    g.add_argument('--y_max', type=float, default=8.0)
    g = p.add_argument_group('optimization')
    g.add_argument('--lr_lora', type=float, default=0.0001)
    g.add_argument('--lr_heads', type=float, default=0.0005)
    g.add_argument('--grad_clip', type=float, default=1.0)
    g.add_argument('--tokens_per_step', type=int, default=100000)
    g.add_argument('--lambda_corr', type=float, default=1.0)
    g.add_argument('--lambda_keep', type=float, default=0.1)
    g.add_argument('--lambda_mag', type=float, default=0.5)
    g.add_argument('--head_warmup_steps', type=int, default=500)
    g.add_argument('--head_warmup_frac', type=float, default=0.15)
    g.add_argument('--head_gain', type=float, default=0.1)
    g.add_argument('--head_gain_ramp', type=int, default=100)
    g = p.add_argument_group('branch pass / memory')
    g.add_argument('--max_branch_turns', type=int, default=16)
    g.add_argument('--n_keep', type=int, default=256)
    g.add_argument('--topk', type=int, default=256)
    g.add_argument('--max_chunk', type=int, default=16384)
    g.add_argument('--vram_target', type=float, default=0.9)
    g.add_argument('--bytes_per_token_prior', type=float, default=0.0)
    g = p.add_argument_group('calibration / eval / logging')
    g.add_argument('--calib_trajs', type=int, default=8)
    g.add_argument('--calib_turns', type=int, default=8)
    g.add_argument('--eval_every_min', type=float, default=45.0)
    g.add_argument('--eval_trajs', type=int, default=8)
    g.add_argument('--final_eval', action=argparse.BooleanOptionalAction, default=True)
    g.add_argument('--shadow_every_min', type=float, default=30.0)
    g.add_argument('--log_every', type=int, default=1)
    g.add_argument('--sys_every', type=int, default=10)
    g.add_argument('--seed', type=int, default=0)
    return p.parse_args(argv)

def main(argv=None):
    a = parse_args(argv)
    from recant import trainer
    trainer.run(a)
if __name__ == '__main__':
    main()